<?php

namespace AppBundle\Repository;

/**
 * propositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class propositionRepository extends \Doctrine\ORM\EntityRepository
{
}
