AppBundle\Entity\demande:
    type: entity
    manyToOne:
            personne:
                targetEntity: AppBundle\Entity\personne
                inversedBy: demandes
                joinColumn:
                    nullable: false
    oneToMany:
            propositions:
                targetEntity: AppBundle\Entity\proposition
                mappedBy: demande
                cascade: [persist]
    table: null
    repositoryClass: AppBundle\Repository\demandeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        texte:
            type: string
            length: 255
        date:
            type: datetime
    lifecycleCallbacks: {  }
