AppBundle\Entity\personne:
    type: entity
    manyToMany:
        competences:
          targetEntity: competence
          joinTable:
            name: personne_competence
            joinColumns:
              personne_id:
                referencedColumnName: id
            inverseJoinColumns:
              competence_id:
                referencedColumnName: id
    oneToMany:
            demandes:
                targetEntity: AppBundle\Entity\demande
                mappedBy: personne
                cascade: [persist]
            propositions:
                targetEntity: AppBundle\Entity\proposition
                mappedBy: personne
                cascade: [persist]
    table: null
    repositoryClass: AppBundle\Repository\personneRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        email:
            type: string
            length: 255
            unique: true
        ville:
            type: string
            length: 255
        numeroTelephone:
            type: integer
            column: numero_telephone
        role:
            type: array
            length: 255
    lifecycleCallbacks: {  }
