AppBundle\Entity\proposition:
    type: entity
    manyToOne:
            personne:
                targetEntity: AppBundle\Entity\personne
                inversedBy: propositions
                joinColumn:
                    nullable: false
            demande:
                targetEntity: AppBundle\Entity\demande
                inversedBy: propositions
                joinColumn:
                    nullable: false

    table: null
    repositoryClass: AppBundle\Repository\propositionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        texte:
            type: string
            length: 255
        date:
            type: datetime
        statut:
            type: boolean
    lifecycleCallbacks: {  }
